### ISSUE TITLE
Doesn't provide base url ?

### ISSUE THREAD

**Issue by johannbuscail** [vordgi/next-impl-getters#29]
I tried each of the methods and none of them returns the base url (ex: `localhost:3000`)
Is there any way to currently do this ?

**Comment by vordgi** [comment]
No, there is no built-in way to get base url. Because we don't know it in static applications. So, there are several ways to solve this problem:

If it's persistent - create an env variable with the base URL and use that;
If it differs, add the user domain to the headers in the middleware and then read from them.

**Comment by markomitranic** [comment]
Afaik you can get "current url" from a vercel env - and only at request time. This is because a single application may be served over multiple urls, so we can't know them during build.

The only way to get a URL during static rendering would be to literally set/construct it yourself, either from an env var, static params or something else. This is what we often do with `next-intl` package, for example.

**Comment by typeofweb** [comment]
You could try reading `workAsyncStorage.getStore()?.incrementalCache?.requestHeaders.host`

**Comment by vordgi** [comment]
I can, but it would be an unstable API that produces different results. For static pages, it won't return anything (as it will execute at build time), and for dynamic pages, it will return the expected domain.

Such logic can be easily implemented through middleware and headers. I consider it the best solution to leave this to the developers.
